### ISSUE TITLE
REPdenovo merging fails

### ISSUE THREAD

**Issue by pbrec** [simoncchu/REPdenovo#1]
Hi,

I tried using REPdenovo and it works fine until merging the different kmer velvet assemblies. While I have 394528 sequences in the contigs.fa_no_dup.fa file, all following _merged_ files and the resulting contigs.fa file is empty. It seems like something in the pipeline is not working correctly.

Any thoughts?

Best,

Philipp

**Comment by pbrec** [comment]
HI Reedwarbler,

I re-compiled TERefiner_1 and ContigsMerger and I am still stuck with the same problem. 
Any idea what could be going on here?

Best,
Philipp

**Comment by simoncchu** [comment]
Hi Philipp,

I just update the ContigsMerger code, please download and compile. After this, would you please run the following command in terminal and see whether it runs with errors:
./ContigsMerger  -s 0.2 -i1 -6.0 -i2 -2.0 -x 15 -k 8 -t 15 -m 1 -o tmp.gml contigs.fa_no_dup.fa > contigs.fa

You may change the number of threads (-t 15) as you want. 
Please let me know how it runs. Thank you.

Best,
Chong

**Comment by simoncchu** [comment]
@pbrec , it usually takes a while when running the merging step. It depends on how repetitive and how large the genome is. So I suggests first pick out some contigs from contigs.fa_no_dup.fa, then test whether some error happens.

**Comment by pbrec** [comment]
Hi Chong,

I ran your updated code on a subset of 1226 contigs. There were no errors reported. However, after merging there were 1686 contigs, which is more than before.

the tmp.gml file might indicate where this behavior originates. It seems like multiple merged contigs (NEW_CONTIG_MERGE) are generated including the same sets of original contigs:

NEW_CONTIG_MERGE_114   NODE_640_length_89_cov_3.011236_25_3260_163025 NODE_4113_length_129_cov_2.968992_25_1630_81510_R

NEW_CONTIG_MERGE_115   NODE_640_length_89_cov_3.011236_25_3260_163025 NODE_182_length_134_cov_3.000000_25_815_40755 NODE_1651_length_82_cov_3.231707_25_1630_81510_R NODE_3_length_110_cov_3.154546_25_52168_1043373_R NODE_3099_length_123_cov_3.073171_25_1630_81510

NEW_CONTIG_MERGE_116   NODE_640_length_89_cov_3.011236_25_3260_163025 NODE_182_length_134_cov_3.000000_25_815_40755 NODE_1651_length_82_cov_3.231707_25_1630_81510_R NODE_3_length_110_cov_3.154546_25_52168_1043373_R NODE_3499_length_111_cov_3.378378_25_1630_81510_R

NEW_CONTIG_MERGE_117   NODE_640_length_89_cov_3.011236_25_3260_163025 NODE_182_length_134_cov_3.000000_25_815_40755 NODE_1651_length_82_cov_3.231707_25_1630_81510_R NODE_3_length_110_cov_3.154546_25_52168_1043373_R NODE_101_length_127_cov_3.070866_25_815_40755_R

NEW_CONTIG_MERGE_118   NODE_640_length_89_cov_3.011236_25_3260_163025 NODE_182_length_134_cov_3.000000_25_815_40755 NODE_1651_length_82_cov_3.231707_25_1630_81510_R NODE_1786_length_228_cov_3.026316_25_815_40755_R

**Comment by simoncchu** [comment]
Hi Philipp,

Yes, there will be more contigs because after merging we concatenate the original ones after the merged ones. If you run from the pipeline, then after the merging step, there will be a step to remove the contained and duplicate ones. So I think if you run from the pipeline, it should be fine now.

Also, we notice that you have 394528 contigs generated. That's  a large number. Perhaps the genome is quite repetitive. Then merging as many as this number of contigs, it will take quite a long time. My suggestion is you can set the "MIN_REPEAT_FREQ" parameter larger, like 100, which means it will assemble repeats with copy number larger than 100, while the default one is 10. 

We are also working on a version that hope can speed up the merging step. Will let you know if done.

**Comment by pbrec** [comment]
Good to know.

Thanks for taking care.

Best,
Philipp

**Comment by simoncchu** [comment]
You are welcome and thanks for the feedback. Any other problems just feel free to let us know.

Best,
Chong
